SELECT * WHERE {
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Software> .
?d2 <http://dbpedia.org/property/platforms> ?o.
?d1 <http://dbpedia.org/property/released> ?o2.
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/VideoGame>.
?d1 <http://dbpedia.org/property/ratings> ?o.
?d1 <http://dbpedia.org/ontology/computingPlatform> ?o1.}