SELECT *   WHERE {
?d1 <http://purl.org/dc/terms/subject> <http://dbpedia.org/resource/Category:Alcohols>.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/class/yago/Alcohols> .
?d1 <http://dbpedia.org/property/routesOfAdministration> ?o.
?d2 <http://dbpedia.org/property/routesOfAdministration> ?o.
?d1 <http://dbpedia.org/ontology/chEBI> ?c1.
?d2 <http://dbpedia.org/property/proteinBound> ?p2.
?d2 <http://dbpedia.org/property/unii> ?u2.
?d2 <http://dbpedia.org/property/stdinchikey> ?s2.
?d1 <http://dbpedia.org/property/smiles> ?sm1.
?d2 <http://dbpedia.org/property/pubchem> ?pu2.
?d2 <http://dbpedia.org/property/molecularWeight> ?m2.
?d1 <http://dbpedia.org/property/kegg> ?k1.
?d1 <http://dbpedia.org/property/excretion> ?e1.
?d1 <http://dbpedia.org/property/drugbank> ?dg1.}