SELECT * WHERE {
?d1 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/Automobile>.
?d1 <http://dbpedia.org/property/weight> ?o.
?d2 <http://dbpedia.org/property/longm> ?o.
?d2 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://dbpedia.org/ontology/ArchitecturalStructure>.
?d1 <http://dbpedia.org/property/engine> ?o1.
?d2 <http://dbpedia.org/ontology/elevation> ?o2.}